### ISSUE TITLE
Adding ace editor in render.html

### ISSUE THREAD

**Issue by aniketkudale** [minikomi/Bootstrap-Form-Builder#134] opened 2016-01-06 10:08 UTC
How to add/integrate custom editor like codemirror or ace editor in render html? 
Ace editor uses external .js file, I have added it into lib/ folder also updated the main.js file! what other changes are to be made?

**Comment by minikomi** [comment] 2016-01-07 07:21
Not a bug / out of scope.

**Closed as completed by minikomi** 2016-01-07 07:21 UTC
